### ISSUE TITLE
the WSGIRequest pickled failed when I use the decorator

### ISSUE THREAD

**Issue by o3o3o** [codeinthehole/django-cacheback#58]
I am using cacheback as the decorator and I wrote my own key function according with our business:
```
Class SthApiCacheJob(FnctionJob):
    def key(self, *args, **kwargs):
        """
        Return the cache key to use.
        Overide Job's key
        """
        prefix = "sth.api"
        if args and len(args)> 2 and hasattr(args[1], 'build_absolute_uri'):
            request = args[1]
            url = hashlib.md5(force_bytes(iri_to_uri(request.build_absolute_uri())))
            key  = "%s.%s:%s" % (prefix, self.class_path, url.hexdigest())
            print "new unique key -------> %s" % (key)
            return key
        else:
            raise RuntimeError("Unable to generate uniq cache key")
```
here is the use case:
```
@cacheback(lifetime=60, fetch_on_miss=True, job_class=SthApiCacheJob)
def v1_dep(request, user=None):
    size = parse_int(request.GET.get('size'), default=5)
    if size<= 0:
        return api_error('invalid_input', _('size is invalid'))
    #sth code....
    return { 'a': a, 'b': b}
```
I got error when running:

```
sth.api.api_sth:v1_dep', <WSGIRequest: GET '/sth/api/v1/dep'>, <SimpleLazyObject: <function <lambda> at 0x10a2db5f0>>), {})
new unique key -------> sth.api.sth.helper.SthApiCacheJob:441fa73b67ae49a151a364a57e00b3b2
2016-05-17 10:01:19,808 cacheback [DEBUG] Job sth.helper.SthApiCacheJob with key 'sth.api.sth.helper.SthApiCacheJob:441fa73b67ae49a151a364a57e00b3b2' - STALE cache hit - triggering async refresh and returning stale result
--before run async_refresh print the call_args-----> type({'kwargs': {'klass_str': 'sth.helper.SthApiCacheJob', 'call_args': ('sth.api.api_sth:v1_dep', <WSGIRequest: GET '/sth/api/v1/dep'>, <SimpleLazyObject: <function <lambda> at 0x10a2db5f0>>), 'obj_kwargs': {'lifetime': 60}, 'obj_args': (), 'call_kwargs': {}}}) is <type 'dict'>
2016-05-17 10:01:19,815 cacheback [ERROR] Unable to trigger task asynchronously - failing over to synchronous refresh
Traceback (most recent call last):
  File "/Users/user/work/ENV/lib/python2.7/site-packages/cacheback/base.py", line 250, in async_refresh
    **self.task_options
  File "/Users/user/work/ENV/lib/python2.7/site-packages/cacheback/utils.py", line 76, in enqueue_task
    return celery_refresh_cache.apply_async(*args, **kwargs)
  File "/Users/user/work/ENV/lib/python2.7/site-packages/celery/app/task.py", line 565, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/Users/user/work/ENV/lib/python2.7/site-packages/celery/app/base.py", line 354, in send_task
    reply_to=reply_to or self.oid, **options
  File "/Users/user/work/ENV/lib/python2.7/site-packages/celery/app/amqp.py", line 310, in publish_task
    **kwargs
  File "/Users/user/work/ENV/lib/python2.7/site-packages/kombu/messaging.py", line 165, in publish
    compression, headers)
  File "/Users/user/work/ENV/lib/python2.7/site-packages/kombu/messaging.py", line 241, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/Users/user/work/ENV/lib/python2.7/site-packages/kombu/serialization.py", line 164, in dumps
    payload = encoder(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/user/work/ENV/lib/python2.7/site-packages/kombu/serialization.py", line 59, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/Users/user/work/ENV/lib/python2.7/site-packages/kombu/serialization.py", line 55, in _reraise_errors
    yield
  File "/Users/user/work/ENV/lib/python2.7/site-packages/kombu/serialization.py", line 164, in dumps
    payload = encoder(data)
  File "/Users/user/work/ENV/lib/python2.7/site-packages/kombu/serialization.py", line 356, in pickle_dumps
    return dumper(obj, protocol=pickle_protocol)
EncodeError: Can't pickle <type 'cStringIO.StringO'>: attribute lookup cStringIO.StringO failed
new unique key -------> sth.api.sth.helper.SthApiCacheJob:441fa73b67ae49a151a364a57e00b3b2
```
my django version: 1.9.5;

I saw the [code](https://github.com/codeinthehole/django-cacheback/blob/master/cacheback/base.py#L87-L96) and I tried to write my  `prepare_args` function , but I found the way is  against the my `key` function.

Please help me. What can I do to solve the problem?

**Comment by o3o3o** [comment]
[The request cannot pickle](http://stackoverflow.com/questions/3103638/pickling-django-request-objects) , I may  should use the decorator on the sub function.
```
def v1_dep(request,user):
     ..
     size = parse_int(request.GET.get('size'), default=5)
      url = hashlib.md5(force_bytes(iri_to_uri(request.build_absolute_uri())))
    return  dep(url, size, user);

@cacheback(lifetime=60, fetch_on_miss=True
def dep(url,size,user):
   ...
  return json;
```

**Comment by stephrdev** [comment]
Yes. I think you don't need to overwrite the key method. What is the problem when using the prepare_args/prepare_kwargs methods?

**Comment by o3o3o** [comment]
After I used the `prepare_args`, I did get the uniq key, but it is still error:  'pickle failed' when `refresh_rsync` calling the  `enqueue_task` with the [code](https://github.com/codeinthehole/django-cacheback/blob/master/cacheback/base.py#L247-L248).

I cannot understand why  WSGIRequest cannot be pickle. [here say it is be locking?](http://stackoverflow.com/questions/3103638/pickling-django-request-objects)

Now, I  use the decorator on the sub function to skip the problem.

Thanks for your reply  @stephrdev
